# Generated by Django 6.0.2 on 2026-03-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('fecha', models.DateField(max_length=8)),
                ('nombre', models.CharField(max_length=100)),
                ('plataforma', models.CharField(max_length=200)),
            ],
        ),
    ]
