# Generated by Django 6.0.2 on 2026-06-24 18:43

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='imagen',
            field=models.ImageField(blank=True, default='profiles/perfil-default.jpg', null=True, upload_to=blog.models.generar_ruta_unica, validators=[blog.models.validar_peso_imagen]),
        ),
    ]
