# Generated by Django 6.0.2 on 2026-06-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='titulo',
            field=models.CharField(default='Post sin título', max_length=45),
            preserve_default=False,
        ),
    ]
