# Generated by Django 6.0.2 on 2026-03-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='imagen',
            field=models.CharField(default='default.jpg', max_length=200),
        ),
    ]
