# Generated by Django 6.0.2 on 2026-07-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_juego_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='categoria',
        ),
        migrations.AddField(
            model_name='juego',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='juegos', to='blog.categoria'),
        ),
    ]
