# Generated by Django 6.0.2 on 2026-07-01 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_juego_categoria_juego_categorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='categorias',
        ),
        migrations.AddField(
            model_name='juego',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.categoria'),
        ),
    ]
