# Generated by Django 6.0.2 on 2026-05-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen_perfil',
            field=models.ImageField(blank=True, default='perfiles/default.jpg', null=True, upload_to='perfiles/'),
        ),
    ]
