# Generated by Django 6.0.2 on 2026-05-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_imagen_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='descripcion',
            field=models.TextField(blank=True, default='¡Hola! estoy en The Glitch Zone.', max_length=300, null=True),
        ),
    ]
